name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62c5b4d2952e1f73f4274f3dc664180e0f6fe4e44978ad4302f07080e2b6ede3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
datapack-folder = "global_packs/required_data/"
