name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f501a50abf998d4173c6b5ebd596b549c8238f9f68b853958323464e2362f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
