name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b760d3237ce6fe85fda3c42d72585ea26b2a8b6b54b28ad8a7a887739369860c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
datapack-folder = "global_packs/required_data/"
