name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af80137e2fe14e2780bf66702edd394cf2f823b255997aad3e22309a4dbcba78"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
datapack-folder = "global_packs/required_data/"
